# Generated by Django 5.0.1 on 2024-01-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutdata',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
