# Generated by Django 5.0.1 on 2024-01-10 09:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='note',
            new_name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
