# Generated by Django 5.0.1 on 2024-01-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_aboutdata_image_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.URLField(default='https://www.example.com'),
            preserve_default=False,
        ),
    ]
